FROM golang:1.23-alpine

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN mkdir -p logs fonts static

RUN go build -o finance_admin ./cmd/admin/main.go

EXPOSE 3000

CMD ["./finance_admin"]